FROM ubuntu:16.04

MAINTAINER M. Adil

RUN apt-get -qq update
RUN apt-get install -y git python wget curl
RUN wget -O - https://repo.saltstack.com/apt/ubuntu/16.04/amd64/latest/SALTSTACK-GPG-KEY.pub | apt-key add -
RUN echo "deb http://repo.saltstack.com/apt/ubuntu/16.04/amd64/latest xenial main" > /etc/apt/sources.list.d/saltstack.list
RUN apt-get update
RUN apt-get install -y salt-minion


VOLUME /var/www/html

EXPOSE 8080


RUN git clone https://github.com/madil88/masterless_minion.git /srv/gitfile
RUN mv /srv/gitfile/masterless.conf /etc/salt/minion.d/masterless.conf

RUN mv /srv/gitfile/salt /srv/
RUN mkdir  /etc/cron.d
RUN /bin/mv /srv/gitfile/salt-standalone-cron /etc/cron.d/salt-standalone-cron
RUN salt-call --local state.highstate


